# Generated by Django 3.0.7 on 2020-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('sub_date', models.DateTimeField(verbose_name='date submitted')),
                ('predicted_rating', models.FloatField()),
            ],
        ),
    ]
